"use client";

import React, { useState } from "react";
import { Search, Share2, Clipboard, Star, Check, X } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// Mock publications data based on PDR fields
const initialPapers = [
  {
    id: "sparse-moe-consensus",
    title: "Decentralized State Sync for Sparse Mixture-of-Experts Nodes",
    authors: "R. Rithish, A. Kowalski, J. Chen",
    category: "Distributed Consensus",
    abstract: "Sparse Mixture-of-Experts (MoE) architectures present unique challenges in wide-area distributed setups. We propose an optimistic state synchronization protocol featuring low-rank weight projection, reducing node synchronization overheads by 60% while maintaining p99 convergence parameters under high package-loss conditions.",
    doi: "10.48550/arXiv.2606.09112",
    citations: 18,
    publishedAt: "June 2026",
    bibtex: `@article{rithish2026sparse,
  title={Decentralized State Sync for Sparse Mixture-of-Experts Nodes},
  author={Rithish, R. and Kowalski, A. and Chen, J.},
  journal={Feenixs Open Science Platform},
  year={2026},
  doi={10.48550/arXiv.2606.09112}
}`
  },
  {
    id: "spectral-embeddings",
    title: "Spectral Projection of High-Dimensional Semantic Embeddings",
    authors: "R. Rithish, H. Neumann",
    category: "NLP & Transformers",
    abstract: "High-dimensional embeddings generated by transformer models incur high storage and search latency. We introduce a manifold projection algorithm using randomized spectral solvers. The resulting embeddings require 60% less storage space with less than 1% degradation in GLUE downstream metrics.",
    doi: "10.48550/arXiv.2605.08415",
    citations: 42,
    publishedAt: "May 2026",
    bibtex: `@article{rithish2026spectral,
  title={Spectral Projection of High-Dimensional Semantic Embeddings},
  author={Rithish, R. and Neumann, H.},
  journal={Journal of Neural Computing},
  year={2026},
  doi={10.48550/arXiv.2605.08415}
}`
  },
  {
    id: "green-telemetry",
    title: "Green Computing: Solar Telemetry and Carbon-Deficit Scheduling",
    authors: "A. Kowalski, S. Patel, J. Chen",
    category: "Green Computing",
    abstract: "Distributed training grids draw significant electrical power from fossil-tied regional grids. We propose a carbon-deficit scheduling algorithm integrated with local solar farm telemetry. When local solar irradiance falls, training tasks shift dynamically to high-irradiance edge nodes globally.",
    doi: "10.48550/arXiv.2604.07221",
    citations: 11,
    publishedAt: "April 2026",
    bibtex: `@article{kowalski2026green,
  title={Green Computing: Solar Telemetry and Carbon-Deficit Scheduling},
  author={Kowalski, A. and Patel, S. and Chen, J.},
  journal={Sustainable Systems Engineering},
  year={2026},
  doi={10.48550/arXiv.2604.07221}
}`
  }
];

// Initial mock comments
const initialComments: Record<string, Array<{ id: string; author: string; rating: number; text: string; date: string }>> = {
  "sparse-moe-consensus": [
    { id: "c1", author: "Dr. Elena Rostova", rating: 5, text: "Excellent mathematical formulation of the weight projection. The convergence proofs hold up nicely under simulated latency spikes.", date: "June 12, 2026" },
    { id: "c2", author: "Marcus Vance", rating: 4, text: "Impressive decrease in node synchronization times. How does this behave when total nodes exceed 50k?", date: "June 20, 2026" }
  ],
  "spectral-embeddings": [
    { id: "c3", author: "Prof. Li Wei", rating: 5, text: "A clean and elegant solution to embedding compression. The GLUE benchmarks look extremely promising.", date: "May 18, 2026" }
  ],
  "green-telemetry": []
};

export default function Research() {
  const [papers] = useState(initialPapers);
  const [comments, setComments] = useState(initialComments);
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedCategory, setSelectedCategory] = useState("All");
  
  // Interactive comment form states
  const [reviewingPaperId, setReviewingPaperId] = useState<string | null>(null);
  const [newAuthor, setNewAuthor] = useState("");
  const [newRating, setNewRating] = useState(5);
  const [newText, setNewText] = useState("");

  // BibTeX overlay state
  const [copiedBibId, setCopiedBibId] = useState<string | null>(null);
  const [activeBibtex, setActiveBibtex] = useState<string | null>(null);

  // Filter papers
  const filteredPapers = papers.filter((paper) => {
    const matchesSearch = paper.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      paper.authors.toLowerCase().includes(searchQuery.toLowerCase()) ||
      paper.abstract.toLowerCase().includes(searchQuery.toLowerCase());
    
    const matchesCategory = selectedCategory === "All" || paper.category === selectedCategory;

    return matchesSearch && matchesCategory;
  });

  const handleCopyBibtex = (bibtex: string, id: string) => {
    navigator.clipboard.writeText(bibtex);
    setCopiedBibId(id);
    setTimeout(() => setCopiedBibId(null), 3000);
  };

  const handleAddReview = (e: React.FormEvent, paperId: string) => {
    e.preventDefault();
    if (!newAuthor || !newText) return;

    const newCommentObj = {
      id: `c_${Date.now()}`,
      author: newAuthor,
      rating: newRating,
      text: newText,
      date: new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })
    };

    setComments((prev) => ({
      ...prev,
      [paperId]: [...(prev[paperId] || []), newCommentObj]
    }));

    // Reset fields
    setNewAuthor("");
    setNewRating(5);
    setNewText("");
    setReviewingPaperId(null);
  };

  return (
    <div className="min-h-screen bg-background text-slate-900 flex flex-col font-sans relative overflow-hidden">
      {/* Background overlay grid */}
      <div className="absolute inset-0 tech-grid pointer-events-none opacity-40 z-0" />
      <div className="absolute -top-[20%] -left-[10%] w-[60%] h-[60%] rounded-full bg-emerald-900/5 blur-[120px] pointer-events-none z-0" />
      <div className="absolute -bottom-[20%] -right-[10%] w-[60%] h-[60%] rounded-full bg-teal-900/5 blur-[120px] pointer-events-none z-0" />

      <Navbar />

      <main className="relative z-10 flex-grow max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-32 pb-24">
        {/* Header Section */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h1 className="text-4xl sm:text-5xl font-extrabold tracking-tight mb-6 text-slate-900 text-glow">
            Research Portal & Publications
          </h1>
          <p className="text-lg text-slate-600 leading-relaxed">
            Discover peer-reviewed papers, citations data, and live reviews. All datasets and model checkbooks are open to academic verification.
          </p>
        </div>

        {/* Search & Filters */}
        <div className="mb-12 space-y-6">
          <div className="relative max-w-2xl mx-auto">
            <Search className="absolute left-4 top-3.5 h-5 w-5 text-slate-400" />
            <input
              type="text"
              placeholder="Search papers by keywords, authors, or abstracts..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-12 pr-4 py-3 bg-white border border-slate-350 rounded-xl text-slate-900 placeholder-slate-400 focus:outline-none focus:border-brand-primary transition-colors text-sm"
            />
          </div>

          <div className="flex flex-wrap justify-center gap-2">
            {["All", "Distributed Consensus", "NLP & Transformers", "Green Computing"].map((cat) => (
              <button
                key={cat}
                onClick={() => setSelectedCategory(cat)}
                className={`px-4 py-2 rounded-lg text-xs font-semibold border transition-all ${
                  selectedCategory === cat
                    ? "bg-brand-primary border-brand-primary text-white shadow-sm"
                    : "bg-white border-slate-200 text-slate-600 hover:text-slate-950"
                }`}
              >
                {cat}
              </button>
            ))}
          </div>
        </div>

        {/* Papers Catalog List */}
        <div className="space-y-8 max-w-5xl mx-auto">
          {filteredPapers.length > 0 ? (
            filteredPapers.map((paper) => (
              <article key={paper.id} className="p-8 rounded-2xl border border-slate-200 bg-white shadow-sm space-y-6">
                {/* Paper Header */}
                <div className="flex flex-col sm:flex-row justify-between items-start gap-4">
                  <div className="space-y-2 text-left">
                    <span className="px-2.5 py-1 rounded bg-emerald-50 border border-emerald-100 text-xs font-mono text-brand-primary font-bold tracking-wide uppercase">
                      {paper.category}
                    </span>
                    <h2 className="text-xl font-bold text-slate-900 hover:text-brand-primary transition-colors mt-2">
                      {paper.title}
                    </h2>
                    <p className="text-xs text-slate-500 italic">Authors: {paper.authors}</p>
                  </div>
                  <div className="text-left sm:text-right shrink-0">
                    <span className="text-sm font-mono font-bold text-brand-primary">{paper.citations} citations</span>
                    <p className="text-[10px] text-slate-500 uppercase tracking-wider font-semibold">Google Scholar Verified</p>
                  </div>
                </div>

                {/* Abstract */}
                <div className="space-y-2 text-left">
                  <h4 className="text-xs font-bold text-slate-950 uppercase tracking-wider font-mono">Abstract</h4>
                  <p className="text-sm text-slate-655 leading-relaxed font-light">{paper.abstract}</p>
                </div>

                {/* Meta details & Citations triggers */}
                <div className="flex flex-wrap items-center justify-between gap-4 pt-4 border-t border-slate-100 text-xs">
                  <div className="flex space-x-6 text-slate-500 font-mono">
                    <span>Published: {paper.publishedAt}</span>
                    <span>DOI: {paper.doi}</span>
                  </div>

                  <div className="flex space-x-3">
                    <button
                      onClick={() => setActiveBibtex(activeBibtex === paper.id ? null : paper.id)}
                      className="px-3.5 py-2 rounded-lg bg-slate-50 border border-slate-200 hover:border-slate-350 hover:bg-slate-100 text-slate-700 transition-colors flex items-center space-x-1.5"
                    >
                      <Share2 className="h-3.5 w-3.5" />
                      <span>BibTeX</span>
                    </button>
                    <button
                      onClick={() => setReviewingPaperId(reviewingPaperId === paper.id ? null : paper.id)}
                      className="px-3.5 py-2 rounded-lg bg-slate-50 border border-slate-200 hover:border-slate-350 hover:bg-slate-100 text-slate-700 transition-colors flex items-center space-x-1.5"
                    >
                      <Star className="h-3.5 w-3.5 text-yellow-500" />
                      <span>Peer Reviews ({comments[paper.id]?.length || 0})</span>
                    </button>
                  </div>
                </div>

                {/* BibTeX copy overlay block */}
                {activeBibtex === paper.id && (
                  <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 relative font-mono text-xs text-brand-primary space-y-3 text-left">
                    <div className="flex justify-between items-center text-slate-500 border-b border-slate-200 pb-2">
                      <span>BibTeX Format</span>
                      <button
                        onClick={() => handleCopyBibtex(paper.bibtex, paper.id)}
                        className="flex items-center space-x-1 hover:text-slate-800 transition-colors"
                      >
                        {copiedBibId === paper.id ? (
                          <>
                            <Check className="h-3.5 w-3.5 text-emerald-605" />
                            <span className="text-emerald-605 font-semibold">Copied!</span>
                          </>
                        ) : (
                          <>
                            <Clipboard className="h-3.5 w-3.5" />
                            <span>Copy</span>
                          </>
                        )}
                      </button>
                    </div>
                    <pre className="overflow-x-auto"><code>{paper.bibtex}</code></pre>
                  </div>
                )}

                {/* Comments / Peer Review System */}
                {reviewingPaperId === paper.id && (
                  <div className="pt-6 border-t border-slate-200 space-y-6 text-left">
                    <div className="flex justify-between items-center">
                      <h4 className="text-sm font-semibold text-slate-900 uppercase tracking-wider font-mono">Verified Peer Reviews</h4>
                      <button 
                        onClick={() => setReviewingPaperId(null)}
                        className="p-1 rounded hover:bg-slate-100 text-slate-500 hover:text-slate-800"
                      >
                        <X className="h-4 w-4" />
                      </button>
                    </div>

                    {/* Review List */}
                    <div className="space-y-4">
                      {comments[paper.id] && comments[paper.id].length > 0 ? (
                        comments[paper.id].map((comm) => (
                          <div key={comm.id} className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-2">
                            <div className="flex justify-between items-center text-xs">
                              <span className="font-semibold text-slate-900">{comm.author}</span>
                              <span className="text-slate-500 font-mono">{comm.date}</span>
                            </div>
                            <div className="flex text-yellow-500">
                              {Array.from({ length: 5 }).map((_, i) => (
                                <Star key={i} className={`h-3 w-3 ${i < comm.rating ? "fill-yellow-500" : "text-slate-250"}`} />
                              ))}
                            </div>
                            <p className="text-sm text-slate-700 font-light leading-relaxed">{comm.text}</p>
                          </div>
                        ))
                      ) : (
                        <p className="text-xs text-slate-500 italic">No reviews submitted yet. Submit a verified review below.</p>
                      )}
                    </div>

                    {/* Leave Review Form */}
                    <form onSubmit={(e) => handleAddReview(e, paper.id)} className="p-5 rounded-xl bg-slate-50 border border-slate-200 space-y-4">
                      <h5 className="text-xs font-semibold text-slate-900 uppercase tracking-wider font-mono">Submit Peer Review</h5>
                      
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                        <div className="space-y-1">
                          <label className="text-[10px] uppercase font-semibold text-slate-500 font-mono">Researcher Name / Title</label>
                          <input
                            type="text"
                            required
                            placeholder="Dr. Jordan Miller"
                            value={newAuthor}
                            onChange={(e) => setNewAuthor(e.target.value)}
                            className="w-full px-3 py-2 bg-white border border-slate-300 rounded text-xs text-slate-900 focus:outline-none focus:border-brand-primary"
                          />
                        </div>
                        <div className="space-y-1">
                          <label className="text-[10px] uppercase font-semibold text-slate-500 font-mono">Evaluation Rating</label>
                          <div className="flex space-x-2 pt-2">
                            {Array.from({ length: 5 }).map((_, i) => {
                              const ratingVal = i + 1;
                              return (
                                <button
                                  type="button"
                                  key={i}
                                  onClick={() => setNewRating(ratingVal)}
                                  className="focus:outline-none"
                                >
                                  <Star className={`h-5 w-5 ${ratingVal <= newRating ? "text-yellow-500 fill-yellow-500" : "text-slate-300"}`} />
                                </button>
                              );
                            })}
                          </div>
                        </div>
                      </div>

                      <div className="space-y-1">
                        <label className="text-[10px] uppercase font-semibold text-slate-500 font-mono">Review Comments</label>
                        <textarea
                          rows={3}
                          required
                          placeholder="Provide details on methodology validation, mathematical clarity, or code replicates..."
                          value={newText}
                          onChange={(e) => setNewText(e.target.value)}
                          className="w-full px-3 py-2 bg-white border border-slate-300 rounded text-xs text-slate-900 placeholder-slate-400 focus:outline-none focus:border-brand-primary resize-none"
                        />
                      </div>

                      <button
                        type="submit"
                        className="px-4 py-2 rounded bg-brand-primary text-white font-semibold text-xs hover:bg-opacity-90 transition-colors"
                      >
                        Submit Verified Review
                      </button>
                    </form>
                  </div>
                )}
              </article>
            ))
          ) : (
            <div className="p-12 text-center rounded-2xl border border-slate-200 bg-slate-50 text-slate-500 italic">
              No publications matching the filters found. Check back later or adjust keywords.
            </div>
          )}
        </div>
      </main>

      <Footer />
    </div>
  );
}
